CREATE TABLE universities(
id SERIAL UNIQUE PRIMARY KEY,
name VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL
);

CREATE ROLE student;
CREATE ROLE teacher;

CREATE TABLE users(
id SERIAL UNIQUE PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
age INT NOT NULL
);